CREATE TABLE Sector (
    name VARCHAR(150) PRIMARY KEY UNIQUE NOT NULL
);

CREATE TABLE Role (
    id INTEGER NOT NULL PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    sector_name VARCHAR(150) REFERENCES Sector(name) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT Unique_Role_Sector UNIQUE (name,sector_name)
);

CREATE TABLE Employee (
    cpf VARCHAR(11) PRIMARY KEY UNIQUE NOT NULL,
    name VARCHAR(150) NOT NULL,
    role_id INTEGER REFERENCES Role(id) ON UPDATE CASCADE ON DELETE SET NULL
);